version: '3.7'
services:
    flask:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        environment:
            - REDIS_HOST=redis
            - MONGO_HOST=mongodb
        depends_on:
            - mongodb
    redis:
        image: redis:5.0.7
        ports:
            - "6379:6379"
    mongodb:
        image: mongo:4.2.3
        ports:
           - "27017:27017"